CREATE TABLE Users (
  ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NULL,
  Address VARCHAR(255) NULL,
  City VARCHAR(50) NULL,
  County VARCHAR(50) NULL,
  Email VARCHAR(100) UNIQUE NOT NULL,
  PhoneNumber VARCHAR(20) NULL,
  Application_ID INT NULL,
  Role_ID INT NULL,
  Created_By VARCHAR(50),
  Created_On DATETIME DEFAULT GETDATE()
);


CREATE TABLE Applications (
  Application_id INT PRIMARY KEY IDENTITY(1,1),
  Name VARCHAR(100) NOT NULL,
  Created_by VARCHAR(50),
  Created_On DATETIME DEFAULT GETDATE()
)

CREATE TABLE Roles (
  Role_ID INT PRIMARY KEY IDENTITY(1,1),
  RoleName VARCHAR(20) NOT NULL,
Created_by VARCHAR(50),
  Created_On DATETIME DEFAULT GETDATE()
);